name: monGARS

options:
  bundleIdPrefix: com.offllm
  deploymentTarget:
    iOS: "18.0"

packages:
  mlx-swift:
    url: https://github.com/ml-explore/mlx-swift
    branch: main
  mlx-swift-examples:
    url: https://github.com/ml-explore/mlx-swift-examples
    branch: main

targets:
  monGARS:
    type: application
    platform: iOS
    deploymentTarget: "18.0"

    sources:
      - path: MyOfflineLLMApp
        excludes:
          - "../node_modules/**"
          - "../build/**"
          - "Pods/**"
          - "MLXCompat.swift"
        # MLXCompat.swift has been removed. The new MLX LLM API is
        # used directly via `LanguageModel` in `MLXModule.swift`.

    dependencies:
      - package: mlx-swift-examples
        product: MLXLLM
      # If your code imports additional MLX products, keep them here:
      - package: mlx-swift
        product: MLX
      - package: mlx-swift
        product: MLXNN
      - package: mlx-swift
        product: MLXLinalg
      - package: mlx-swift
        product: MLXFFT
      # Additional libraries required by MLXModule.swift
      - package: mlx-swift-examples
        product: MLXLMCommon
      # - package: mlx-swift-examples
      #   product: Tokenizers

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.offllm.mongars
        INFOPLIST_FILE: MyOfflineLLMApp/Info.plist
        SWIFT_VERSION: "6.0"
        IPHONEOS_DEPLOYMENT_TARGET: "18.0"
        SWIFT_OBJC_BRIDGING_HEADER: MyOfflineLLMApp/Bridging/monGARS-Bridging-Header.h

        # Unsigned/device builds in CI
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: ""
        DEVELOPMENT_TEAM: ""

        # Stable toolchain for RN/Folly
        CLANG_CXX_LIBRARY: libc++
        CLANG_CXX_LANGUAGE_STANDARD: c++17
        OTHER_MTLFLAGS:
          - "$(inherited)"
          - "-Wno-c++17-extensions"

        # Allow CocoaPods header symlink scripts to write in Xcode 15+
        ENABLE_USER_SCRIPT_SANDBOXING: NO

      configurations:
        Release:
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym

    scripts:
      - name: Create Symlinks to Header Folders
        script: |
          echo "Symlinks handled by CocoaPods"
          exit 0
        outputFiles:
          - "${DERIVED_FILE_DIR}/create_symlinks_to_header_folders.stamp"
        runOnlyForDeploymentPostprocessing: false
        alwaysOutOfDate: true

    scheme:
      testTargets: []
