name: Reset iOS caches
description: Remove derived data caches and prepare a fresh module cache directory for iOS builds.
inputs: {}
outputs:
  module_cache_dir:
    description: "Path to the temporary module cache directory created for this run."
    value: ${{ steps.prepare.outputs.module_cache_dir }}
runs:
  using: composite
  steps:
    - id: prepare
      shell: bash
      run: |
        set -euo pipefail
        rm -rf ~/Library/Developer/Xcode/DerivedData
        rm -rf ~/Library/Caches/com.apple.dt.Xcode
        rm -rf build/DerivedData
        rm -rf build/DerivedData/ModuleCache.noindex
        rm -rf build/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates
        rm -rf build/DerivedData/Build/Intermediates.noindex/PrecompiledHeaders
        MODULE_CACHE_DIR="$(mktemp -d)"
        echo "MODULE_CACHE_DIR=${MODULE_CACHE_DIR}" >> "$GITHUB_ENV"
        echo "CLANG_MODULE_CACHE_PATH=${MODULE_CACHE_DIR}" >> "$GITHUB_ENV"
        echo "module_cache_dir=${MODULE_CACHE_DIR}" >> "$GITHUB_OUTPUT"
