name: Verify iOS build configuration
description: Run RN/Hermes and C++20 verification scripts to detect drift.
runs:
  using: "composite"
  steps:
    - name: Verify RN/Hermes versions match package.json
      shell: bash
      run: python3 scripts/verify-ios-rn-versions.py
    - name: Verify Pods use C++20
      shell: bash
      run: python3 scripts/verify-ios-cpp-standard.py
