name: MyOfflineLLMApp

options:
  bundleIdPrefix: com.offllm
  # Ensure standard configs exist for XcodeGen
  configs:
    Debug: debug
    Release: release
  createIntermediateGroups: true
  minimumXcodeGenVersion: 2.40.0

settings:
  base:
    # React Native 0.81.x mandates iOS 18.0+. Keep this in sync with RN's
    # minimum supported version to avoid build or CocoaPods issues.
    IPHONEOS_DEPLOYMENT_TARGET: 18.0
    SWIFT_VERSION: 5.10
    HEADER_SEARCH_PATHS: "$(inherited)"
    LIBRARY_SEARCH_PATHS: "$(inherited)"
    "EXCLUDED_ARCHS[sdk=iphonesimulator*]": "x86_64" # force arm64-only simulator builds
    ENABLE_USER_SCRIPT_SANDBOXING: NO

packages:
  MLX:
    url: https://github.com/ml-explore/mlx-swift.git
    exactVersion: 0.25.6
  MLXLibraries:
    url: https://github.com/ml-explore/mlx-swift-examples
    exactVersion: 2.25.6 # exposes the MLXLLM product

targets:
  MyOfflineLLMApp:
    type: application
    platform: iOS
    # Make Xcode use our stub xcconfigs that include the Pods-generated ones
    configFiles:
      Debug: Config/MyOfflineLLMApp.Debug.xcconfig
      Release: Config/MyOfflineLLMApp.Release.xcconfig
      # (Optional) If you have other configs like Profile, add them here pointing
      # to stubs that include the matching Pods .xcconfig
    # Match the project's deployment target to React Native's minimum (18.0)
    # so generated pods do not demand a higher iOS version.
    deploymentTarget: "18.0"
    sources:
      - path: MyOfflineLLMApp
        excludes:
          - "Pods/**"
          - MLXTurboModule.mm # remove brittle ObjC++ bridge
      - path: build/generated/ios
        optional: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.offllm.myofflinellmapp
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        CLANG_ENABLE_MODULES: YES
        # Swift <-> ObjC: keep bridging header path stable
        SWIFT_OBJC_BRIDGING_HEADER: $(SRCROOT)/MyOfflineLLMApp/MyOfflineLLMApp-Bridging-Header.h
        HEADER_SEARCH_PATHS:
          - $(inherited)
          - $(SRCROOT)/build/generated/ios
          - $(PODS_ROOT)/Headers/Public/**
          - $(PODS_CONFIGURATION_BUILD_DIR)/ReactCommon/**
          - $(SRCROOT)/../node_modules/react-native/ReactCommon/**
        # USE_HEADERMAP/ALWAYS_SEARCH_USER_PATHS are set globally via Podfile post_install
        SWIFT_INCLUDE_PATHS:
          - $(SRCROOT)/build/generated/ios
    dependencies:
      - package: MLX
        product: MLX
      - package: MLXLibraries
        product: MLXLLM
    scripts:
      - name: Create Symlinks to Header Folders
        script: echo "Symlinks handled by CocoaPods"
        outputFiles:
          - "${DERIVED_FILE_DIR}/create_symlinks_to_header_folders.stamp"
        runOnlyForDeploymentPostprocessing: false
        alwaysOutOfDate: true
      - name: "[CP] Copy XCFrameworks"
        script: echo "Copy XCFrameworks handled by CocoaPods"
        outputFiles:
          - "${DERIVED_FILE_DIR}/copy_xcframeworks.stamp"
    scheme:
      testTargets: []
