name: monGARS

options:
  bundleIdPrefix: com.27pm

targets:
  monGARS:
    type: application
    platform: iOS
    deploymentTarget: "18.0"

    sources:
      - path: MyOfflineLLMApp
        excludes:
          - "../node_modules/**"
          - "../build/**"
          - "Pods/**"

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.27pm.monGARS
        INFOPLIST_FILE: MyOfflineLLMApp/Info.plist
        SWIFT_VERSION: 5.0
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: ""
        DEVELOPMENT_TEAM: ""

        # 👇 ensure C++ compatibility with libc++ on iOS 18 toolchains
        CLANG_CXX_LANGUAGE_STANDARD: gnu++20
        OTHER_CPLUSPLUSFLAGS: $(inherited) -D_LIBCPP_ENABLE_CXX20_REMOVED_TYPEDEF_MACROS

        HEADER_SEARCH_PATHS:
          - $(inherited)
          - $(SRCROOT)/../node_modules/react-native/React
          - $(SRCROOT)/../node_modules/react-native/React/**

    scheme:
      testTargets: []
