name: MyOfflineLLMApp

options:
  bundleIdPrefix: com.offllm
  createIntermediateGroups: true

settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 14.0
    SWIFT_VERSION: 5.0
    HEADER_SEARCH_PATHS: "$(inherited)"
    LIBRARY_SEARCH_PATHS: "$(inherited)"

targets:
  MyOfflineLLMApp:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: MyOfflineLLMApp
        excludes:
          - "Pods/**"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.offllm.myofflinellmapp
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
    scheme:
      testTargets: []
