name: MyOfflineLLMApp

options:
  bundleIdPrefix: com.offllm
  createIntermediateGroups: true
  minimumXcodeGenVersion: 2.40.0

settings:
  base:
    # The deployment target must be kept in sync with React Native's minimum
    # supported iOS version.  React Native 0.81.x requires iOS 18.0 or newer.
    IPHONEOS_DEPLOYMENT_TARGET: 18.0
    SWIFT_VERSION: 5.10
    HEADER_SEARCH_PATHS: "$(inherited)"
    LIBRARY_SEARCH_PATHS: "$(inherited)"

packages:
  MLX:
    url: https://github.com/ml-explore/mlx-swift.git
    from: 0.25.6
  MLXLibraries:
    url: https://github.com/ml-explore/mlx-swift-examples
    from: 2.25.6 # exposes the MLXLLM product

targets:
  MyOfflineLLMApp:
    type: application
    platform: iOS
    # Bump the app's deployment target to match the minimum supported iOS
    # version for React Native.  This avoids CocoaPods resolution errors when
    # installing generated pods (e.g. `ReactAppDependencyProvider`) which
    # specify a higher deployment target.
    deploymentTarget: "18.0"
    sources:
      - path: MyOfflineLLMApp
        excludes:
          - "Pods/**"
          - MLXTurboModule.mm # remove brittle ObjC++ bridge
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.offllm.myofflinellmapp
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
    dependencies:
      - package: MLX
        product: MLX
      - package: MLXLibraries
        product: MLXLLM
    scheme:
      testTargets: []
