name: monGARS

options:
  bundleIdPrefix: com.27pm

targets:
  monGARS:
    type: application
    platform: iOS
    deploymentTarget: "18.0"

    # Use the existing React Native iOS app folder.
    # Your repo already has ios/MyOfflineLLMApp/* (Info.plist, AppDelegate, etc.).
    # XcodeGen runs from the ios/ directory, so this points to ios/MyOfflineLLMApp.
    sources:
      - path: MyOfflineLLMApp
        excludes:
          - "../node_modules/**"
          - "../build/**"
          - "Pods/**"

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.27pm.monGARS
        INFOPLIST_FILE: MyOfflineLLMApp/Info.plist
        SWIFT_VERSION: 5.0

        # Ensure the unsigned, device-target build does not require signing in CI
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: ""
        DEVELOPMENT_TEAM: ""

        # Typical RN include paths; keep them lenient
        HEADER_SEARCH_PATHS:
          - $(inherited)
          - $(SRCROOT)/../node_modules/react-native/React
          - $(SRCROOT)/../node_modules/react-native/React/**

    scheme:
      testTargets: []
