name: monGARS

options:
  bundleIdPrefix: com.27pm

targets:
  monGARS:
    type: application
    platform: iOS
    deploymentTarget: "18.0"

    sources:
      - path: MyOfflineLLMApp
        excludes:
          - "../node_modules/**"
          - "../build/**"
          - "Pods/**"

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.27pm.monGARS
        INFOPLIST_FILE: MyOfflineLLMApp/Info.plist
        SWIFT_VERSION: 5.0

        # Unsigned/device CI
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: ""
        DEVELOPMENT_TEAM: ""

        # Stable toolchain for RN/Folly
        CLANG_CXX_LIBRARY: libc++
        CLANG_CXX_LANGUAGE_STANDARD: gnu++17

        HEADER_SEARCH_PATHS:
          - $(inherited)
          - $(SRCROOT)/../node_modules/react-native/React
          - $(SRCROOT)/../node_modules/react-native/React/**

    scripts:
      - name: Create Symlinks to Header Folders
        script: |
          echo "Symlinks handled by CocoaPods"
          exit 0
        outputFiles:
          - "${DERIVED_FILE_DIR}/create_symlinks_to_header_folders.stamp"
        runOnlyForDeploymentPostprocessing: false
        alwaysOutOfDate: true

    scheme:
      testTargets: []
