name: monGARS

options:
  bundleIdPrefix: com.offllm
  deploymentTarget:
    iOS: "18.0"

packages:
  mlx-swift:
    url: https://github.com/ml-explore/mlx-swift
    from: 0.10.0

targets:
  monGARS:
    type: application
    platform: iOS
    deploymentTarget: "18.0"

    sources:
      - path: MyOfflineLLMApp
        excludes:
          - "../node_modules/**"
          - "../build/**"
          - "Pods/**"

    dependencies:
      - package: mlx-swift
        product: MLX

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.offllm.monGARS
        INFOPLIST_FILE: MyOfflineLLMApp/Info.plist
        SWIFT_VERSION: 5.0

        # Unsigned/device builds in CI
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: ""
        DEVELOPMENT_TEAM: ""

        # Stable toolchain for RN/Folly
        CLANG_CXX_LIBRARY: libc++
        CLANG_CXX_LANGUAGE_STANDARD: gnu++17

        # Allow CocoaPods header symlink scripts to write in Xcode 15+
        ENABLE_USER_SCRIPT_SANDBOXING: NO

      configurations:
        Release:
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym

    scripts:
      - name: Create Symlinks to Header Folders
        script: |
          echo "Symlinks handled by CocoaPods"
          exit 0
        outputFiles:
          - "${DERIVED_FILE_DIR}/create_symlinks_to_header_folders.stamp"
        runOnlyForDeploymentPostprocessing: false
        alwaysOutOfDate: true

    scheme:
      testTargets: []
