name: iOS Setup
description: Select Xcode, install Node deps, XcodeGen and CocoaPods
runs:
  using: "composite"
  steps:
    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "16.4"

    - name: Setup Node 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "npm"

    - name: Install JS deps
      shell: bash
      run: npm ci

    - name: Install XcodeGen (prebuilt)
      shell: bash
      run: |
        set -eux
        VER="2.39.1"
        curl -L "https://github.com/yonaskolb/XcodeGen/releases/download/${VER}/xcodegen.zip" -o /tmp/xg.zip
        unzip -q /tmp/xg.zip -d /tmp/xg
        XCODEGEN_BIN=$(find /tmp/xg -type f -name xcodegen -perm -111 | head -n 1)
        XCODEGEN_DIR=$(dirname "$(dirname "$XCODEGEN_BIN")")
        INSTALL_BIN_DIR="/opt/homebrew/bin"
        INSTALL_SHARE_DIR="/opt/homebrew/share"
        sudo mkdir -p "$INSTALL_BIN_DIR" "$INSTALL_SHARE_DIR"
        sudo mv "$XCODEGEN_BIN" "$INSTALL_BIN_DIR/xcodegen"
        sudo mv "$XCODEGEN_DIR/share/XcodeGen" "$INSTALL_SHARE_DIR"
        chmod +x "$INSTALL_BIN_DIR/xcodegen"
        echo "$INSTALL_BIN_DIR" >> "$GITHUB_PATH"
        "$INSTALL_BIN_DIR/xcodegen" --version

    - name: Install CocoaPods
      shell: bash
      run: |
        gem install cocoapods --no-document
        pod --version
