name: iOS setup
description: Shared steps for iOS builds
inputs:
  node-version:
    description: Node version
    required: false
    default: "18"
  xcode-version:
    description: Xcode version
    required: false
    default: "16.4"
  xcodegen-version:
    description: XcodeGen version
    required: false
    default: "2.39.1"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Select Xcode ${{ inputs.xcode-version }}
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ inputs.xcode-version }}
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
    - name: Install dependencies
      run: npm ci
      shell: bash
    - name: Install XcodeGen (prebuilt)
      shell: bash
      run: |
        set -euxo pipefail
        VER="${{ inputs.xcodegen-version }}"
        curl -L "https://github.com/yonaskolb/XcodeGen/releases/download/${VER}/xcodegen-${VER}.zip" -o /tmp/xg.zip
        unzip -q /tmp/xg.zip -d /tmp/xg
        sudo mv /tmp/xg/xcodegen /usr/local/bin/xcodegen
        xcodegen --version
    - name: Install CocoaPods
      shell: bash
      run: |
        gem install cocoapods --no-document
        pod --version
    - name: Generate Xcode project & Install Pods
      shell: bash
      run: |
        (cd ios/MyOfflineLLMApp && xcodegen generate)
        perl -0 -i -pe 's/objectVersion = \d+/objectVersion = 56/' ios/MyOfflineLLMApp/MyOfflineLLMApp.xcodeproj/project.pbxproj
        pod repo update
        (cd ios && pod install --repo-update)
