name: iOS Setup
description: Select Xcode, install Node deps, XcodeGen and CocoaPods
runs:
  using: "composite"
  steps:
    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "16.4"

    - name: Setup Node 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "npm"

    - name: Install JS deps
      shell: bash
      run: npm ci

    - name: Install XcodeGen (pkg)
      shell: bash
      run: |
        set -eux
        VER="2.39.1"
        curl -L "https://github.com/yonaskolb/XcodeGen/releases/download/${VER}/XcodeGen.pkg" -o /tmp/xcodegen.pkg
        sudo installer -pkg /tmp/xcodegen.pkg -target /
        xcodegen --version

    - name: Install CocoaPods
      shell: bash
      run: |
        gem install cocoapods --no-document
        pod --version
