name: iOS Setup
description: Select Xcode, install Node deps, XcodeGen and CocoaPods
runs:
  using: "composite"
  steps:
    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "16.4"

    - name: Setup Node 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "npm"

    - name: Install JS deps
      shell: bash
      run: npm ci

    - name: Install XcodeGen (prebuilt)
      shell: bash
      run: |
        set -eux
        VER="2.39.1"
        curl -L "https://github.com/yonaskolb/XcodeGen/releases/download/${VER}/xcodegen.zip" -o /tmp/xg.zip
        unzip -q /tmp/xg.zip -d /tmp/xg
        echo "Contents of /tmp/xg:"
        ls -la /tmp/xg
        echo "Contents of /tmp/xg/xcodegen:"
        ls -la /tmp/xg/xcodegen
        echo "Contents of /tmp/xg/xcodegen/bin:"
        ls -la /tmp/xg/xcodegen/bin
        chmod +x /tmp/xg/xcodegen/bin/xcodegen
        INSTALL_DIR="/opt/homebrew/bin"
        sudo mkdir -p "$INSTALL_DIR"
        sudo mv /tmp/xg/xcodegen/bin/xcodegen "$INSTALL_DIR/xcodegen"
        echo "$INSTALL_DIR" >> "$GITHUB_PATH"
        /opt/homebrew/bin/xcodegen --version

    - name: Install CocoaPods
      shell: bash
      run: |
        gem install cocoapods --no-document
        pod --version
