//  MyOfflineLLMApp.h
//  Generated by ChatGPT
//
//  This umbrella header exposes the public interface of the
//  MyOfflineLLMApp framework.  It defines version symbols required
//  by Xcode when `DEFINES_MODULE` is enabled.  Additional public
//  headers can be imported here as needed.

#import <Foundation/Foundation.h>

//! Project version number for MyOfflineLLMApp.
FOUNDATION_EXPORT double MyOfflineLLMAppVersionNumber;

//! Project version string for MyOfflineLLMApp.
FOUNDATION_EXPORT const unsigned char MyOfflineLLMAppVersionString[];

// In this header you should import all the public headers of your framework using
// statements like #import <MyOfflineLLMApp/PublicHeader.h>
