// MyOfflineLLMApp-Bridging-Header.h
// Expose React's ObjC types to Swift without importing React as a Swift module.
#import <React/RCTBridgeModule.h>
#import <React/RCTEventEmitter.h>
#import <React/RCTLog.h>
// The LLMSpec header is generated by React Native Codegen when New Architecture is on.
// Depending on your Pod/Codegen layout it may appear as a module-mapped header
// (<AppSpec/LLMSpec.h>) OR as a flat header in the build-generated folder.
#if __has_include(<AppSpec/LLMSpec.h>)
#import <AppSpec/LLMSpec.h>
#elif __has_include("LLMSpec.h")
#import "LLMSpec.h"
#else
// If neither path exists yet, keep compiling. The actual source that uses LLMSpec
// should also gate on RCT_NEW_ARCH_ENABLED to avoid symbol use when not available.
#pragma message("Note: LLMSpec.h not found at compile-time; continuing without it.")
#endif

