platform :ios, '13.0'

require_relative '../../node_modules/react-native/scripts/react_native_pods'
require_relative '../../node_modules/@react-native-community/cli-platform-ios/native_modules'

project 'MyOfflineLLMApp.xcodeproj'

target 'MyOfflineLLMApp' do
  use_frameworks!
  use_react_native!(
    :path => '../../node_modules/react-native'
  )

  pod 'boost', :git => 'https://github.com/react-native-community/boost-for-react-native.git', :tag => '1.76.0'
end
