platform :ios, '15.0'

require_relative '../../node_modules/react-native/scripts/react_native_pods'
require_relative '../../node_modules/@react-native-community/cli-platform-ios/native_modules'

project 'MyOfflineLLMApp.xcodeproj'

target 'MyOfflineLLMApp' do
  use_frameworks!
  # Use React Native's vendored Boost podspec to avoid source conflicts

  use_react_native!(
    :path => '../../node_modules/react-native'
  )
end
