name: MyOfflineLLMApp

options:
  minimumXcodeGenVersion: 2.40.0

packages:
  MLX:
    url: https://github.com/ml-explore/mlx-swift.git
    from: 0.25.6
  MLXLibraries:
    url: https://github.com/ml-explore/mlx-swift-examples
    from: 2.25.6 # exposes the MLXLLM product

targets:
  MyOfflineLLMApp:
    type: application
    platform: iOS
    # Align the deployment target with the main project. React Native
    # currently requires iOS 18.0 or higher, so bump this target to prevent
    # generated pods from requiring a higher version than the project.
    deploymentTarget: "18.0"
    settings:
      SWIFT_VERSION: 5.10
      SWIFT_OBJC_BRIDGING_HEADER: MyOfflineLLMApp/MyOfflineLLMApp-Bridging-Header.h
    sources:
      - path: .
    dependencies:
      - package: MLX
        product: MLX
      - package: MLXLibraries
        product: MLXLLM
