name: MyOfflineLLMApp
options:
  bundleIdPrefix: com.offllm
  xcodeVersion: "15.4"
targets:
  MyOfflineLLMApp:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - path: .
        excludes:
          - project.yml
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.offllm.MyOfflineLLMApp
      HEADER_SEARCH_PATHS:
        - "$(PROJECT_DIR)/../../node_modules/react-native/React/**"
