name: MyOfflineLLMApp
options:
  bundleIdPrefix: com.offllm
  xcodeVersion: "15.4"
  postGenCommand: pod install
targets:
  MyOfflineLLMApp:
    type: framework
    platform: iOS
    deploymentTarget: "15.0"
    info:
      path: Info.plist
      properties:
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleName: MyOfflineLLMApp
        CFBundleShortVersionString: 1.0.0
        CFBundleVersion: 1
    sources:
      - path: .
        excludes:
          - project.yml
    headers:
      public:
        - MyOfflineLLMApp.h
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.offllm.MyOfflineLLMApp
      HEADER_SEARCH_PATHS:
        - "$(PROJECT_DIR)/../../node_modules/react-native/React/**"
      DEFINES_MODULE: YES
