name: MyOfflineLLMApp

options:
  minimumXcodeGenVersion: 2.40.0

packages:
  MLX:
    url: https://github.com/ml-explore/mlx-swift.git
    from: 0.25.6
  MLXLibraries:
    url: https://github.com/ml-explore/mlx-swift-examples
    from: 2.25.6 # exposes the MLXLLM product

targets:
  MyOfflineLLMApp:
    type: application
    platform: iOS
    # Align with the parent project's deployment target. React Native 0.81.x
    # requires iOS 18.0+, so keep this target in sync to avoid pod mismatches.
    deploymentTarget: "18.0"
    settings:
      SWIFT_VERSION: 5.10
      SWIFT_OBJC_BRIDGING_HEADER: MyOfflineLLMApp/MyOfflineLLMApp-Bridging-Header.h
    sources:
      - path: .
    dependencies:
      - package: MLX
        product: MLX
      - package: MLXLibraries
        product: MLXLLM
