name: Android

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
  workflow_call:

permissions:
  contents: read

concurrency:
  group: android-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max_old_space_size=4096
      ORG_GRADLE_PROJECT_javaToolchain: 17

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node (cache npm)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install JS deps
        run: npm ci

      - name: Generate Turbo headers
        run: npm run codegen || true

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Assemble Release
        working-directory: android
        run: ./gradlew assembleRelease

      - name: Upload APKs/AABs
        uses: actions/upload-artifact@v4
        with:
          name: monGARS-android-artifacts
          path: |
            android/app/build/outputs/apk/release/**/*.apk
            android/app/build/outputs/bundle/release/**/*.aab
