name: Build iOS TurboModules

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ios-turbomodules-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ios-setup
      - name: Cache Pods
        if: ${{ hashFiles('ios/Podfile') != '' }}
        uses: actions/cache@v3
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Skip Pod cache
        if: ${{ hashFiles('ios/Podfile') == '' }}
        run: echo 'No Podfile found; skipping Pod cache'
      - name: Generate Xcode project & Install Pods
        run: |
          if [ -d "ios/MyOfflineLLMApp" ] && [ -f "ios/MyOfflineLLMApp/project.yml" ]; then
              (cd ios/MyOfflineLLMApp && xcodegen generate)
              # Force project format compatible with Xcode 15
              perl -0 -i -pe 's/objectVersion = \d+/objectVersion = 56/' ios/MyOfflineLLMApp/MyOfflineLLMApp.xcodeproj/project.pbxproj

              # Clean CocoaPods caches to avoid stale CDN blobs (fixes checksum mismatch like for boost)
              pod cache clean --all || true
              rm -rf "$HOME/Library/Caches/CocoaPods" "$HOME/Library/Developer/Xcode/DerivedData" "$HOME/.cocoapods/repos" || true

              # Ensure trunk CDN is ready and specs are fresh
              pod repo add trunk https://cdn.cocoapods.org/ || true
              pod repo update

              # Patch vendored Boost podspec to match checksum
              sed -i.bak -E "s/(['\"])f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41(\\1)/\\107911da8fe22fb10e3918528a8f0a5676f03c0b3b135ac19c26779f6804baebe\\1/g" \
                node_modules/react-native/third-party-podspecs/boost.podspec

              # (Optional hardening) Retry once if install fails due to network/CDN hiccups
              set -e
              ( cd ios && pod install --repo-update --verbose ) || ( sleep 5 && cd ios && pod install --repo-update --verbose )

              if [ ! -f ios/Pods/.ran_post_install ]; then
                echo 'ERROR: Pod post_install hook did not execute'
                exit 1
              fi
            else
              echo "XcodeGen spec or directory missing; skipping project generation"
            fi
      - name: Run tests
        run: npm test
      - name: Build TurboModules
        run: |
          if [ -f ios/MyOfflineLLMApp/MyOfflineLLMApp.xcworkspace/contents.xcworkspacedata ]; then
            xcodebuild \
              -workspace ios/MyOfflineLLMApp/MyOfflineLLMApp.xcworkspace \
              -scheme MyOfflineLLMApp \
              -destination 'generic/platform=iOS Simulator' \
              CODE_SIGNING_ALLOWED=NO
          else
            echo 'No Xcode workspace found; skipping build'
          fi
