name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  js-ci:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max_old_space_size=4096
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.4
          cache: npm

      - name: Install deps from lockfile
        run: npm ci

      - name: Generate Turbo headers (no-op if none)
        run: |
          set -euo pipefail
          export CODEGEN_OUTPUT_DIR="${CODEGEN_OUTPUT_DIR:-$(pwd)/ios/build/generated}"
          export TEMPLATE_SRC_DIR="${TEMPLATE_SRC_DIR:-$(pwd)/src/specs}"
          npm run codegen

      - name: Format check
        run: npm run format:check

      - name: Unit tests
        run: npm run test:ci

      - name: Run ESLint (no warnings allowed)
        run: npm run lint:ci

  ios-ci:
    runs-on: macos-14
    env:
      NODE_OPTIONS: --max_old_space_size=4096
    steps:
      - uses: actions/checkout@v4

      # ---- Xcode selection & guard ----
      - name: Select Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Verify Xcode is >= 16.1
        run: |
          set -euo pipefail
          VER=$(xcodebuild -version | awk '/Xcode/ {print $2}')
          echo "Selected Xcode: $VER"
          [[ "$VER" =~ ^16\. ]] || { echo "❌ Requires Xcode 16.x"; exit 1; }

      # ---- Node & JS deps + Codegen BEFORE pods ----
      - name: Setup Node (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.4
          cache: npm

      - name: Install JS deps from lockfile
        run: npm ci

      - name: Generate Turbo headers (no-op if none)
        run: |
          set -euo pipefail
          export CODEGEN_OUTPUT_DIR="${CODEGEN_OUTPUT_DIR:-$(pwd)/ios/build/generated}"
          export TEMPLATE_SRC_DIR="${TEMPLATE_SRC_DIR:-$(pwd)/src/specs}"
          npm run codegen || true

      # ---- Ensure an .xcodeproj exists (optional) ----
      - name: Install XcodeGen
        run: brew install xcodegen || true

      - name: Generate Xcode project (if project.yml exists)
        run: |
          set -euo pipefail
          if [ -f ios/project.yml ]; then
            (cd ios && xcodegen generate)
          fi

      # ---- CocoaPods without Bundler (avoid 3.3 gemset conflicts) ----
      - name: CocoaPods repo update (best-effort)
        run: pod repo update || true

      - name: Pod install
        run: |
          set -euo pipefail
          cd ios
          pod install --repo-update

      # ---- Harden script phases & scrub Hermes warnings ----
      - name: Harden phases & remove Hermes “Replace Hermes”
        run: |
          set -euo pipefail
          cd ios

          # Ensure xcodeproj gem is available for the script
          ruby -e "require 'rubygems'; begin; require 'xcodeproj'; rescue LoadError; system('gem install xcodeproj -v \"~>1.27\" --no-document'); require 'xcodeproj'; end"

          ruby - <<'RUBY'
            require 'xcodeproj'

            def harden(path)
              return unless File.exist?(path)
              proj = Xcodeproj::Project.open(path)
              proj.targets.each do |t|
                # Add a harmless derived output to silence "will run every build"
                t.shell_script_build_phases.each do |p|
                  if (p.output_paths.nil? || p.output_paths.empty?) && (p.files_references.nil? || p.files_references.empty?)
                    safe = (p.name || "Phase").gsub(/\W/,'_')
                    p.output_paths = ["$(DERIVED_FILE_DIR)/#{safe}.touch"]
                  end
                  # Prefer outputs-driven runs over "Always run"
                  if p.respond_to?(:always_out_of_date) && p.always_out_of_date == '1'
                    p.always_out_of_date = '0'
                  end
                end

                # Remove Hermes "Replace Hermes" phases if present
                t.shell_script_build_phases
                  .select { |p| (p.name || '') =~ /\[Hermes\]\s*Replace Hermes/i }
                  .each { |p| t.build_phases.delete(p) }
              end
              proj.save
            end

            harden('Pods/Pods.xcodeproj')
            harden('MyOfflineLLMApp.xcodeproj')
          RUBY

          # Assert Hermes phase is gone
          if grep -Riq --include=project.pbxproj "Replace Hermes" Pods MyOfflineLLMApp.xcodeproj; then
            echo "::error::Hermes 'Replace Hermes' phase still present after hardening"
            exit 1
          fi

      # ---- Build (Debug, Simulator) with a valid destination ----
      - name: Show available simulator destinations (debug aid)
        run: |
          xcodebuild -workspace ios/MyOfflineLLMApp.xcworkspace \
                     -scheme MyOfflineLLMApp \
                     -configuration Debug \
                     -showdestinations || true

      - name: Clean & Build (Debug, iPhone 16 Pro / iOS 18.2)
        run: |
          set -euo pipefail
          mkdir -p build
          cd ios

          xcodebuild clean \
            -workspace MyOfflineLLMApp.xcworkspace \
            -scheme MyOfflineLLMApp \
            -configuration Debug

          xcodebuild \
            -workspace MyOfflineLLMApp.xcworkspace \
            -scheme MyOfflineLLMApp \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.2' \
            -resultBundlePath ../build/MyOfflineLLMApp.xcresult \
            build | tee ../build/xcodebuild.log

      # ---- Upload artifacts ----
      - name: Upload build logs & result bundle
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-outputs
          path: |
            build/xcodebuild.log
            build/MyOfflineLLMApp.xcresult
          if-no-files-found: warn
          compression-level: 6

  ios-ipa:
    runs-on: macos-14
    needs: ios-ci
    env:
      NODE_OPTIONS: --max_old_space_size=4096
    steps:
      - uses: actions/checkout@v4

      # ---- Xcode selection for device archive ----
      - name: Select Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Verify Xcode is >= 16.1
        run: |
          set -euo pipefail
          VER=$(xcodebuild -version | awk '/Xcode/ {print $2}')
          echo "Selected Xcode: $VER"
          [[ "$VER" =~ ^16\. ]] || { echo "❌ Requires Xcode 16.x"; exit 1; }

      # ---- Node / JS deps & Codegen BEFORE pods ----
      - name: Setup Node (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.4
          cache: npm

      - name: Install JS deps from lockfile
        run: npm ci

      - name: Generate Turbo headers (no-op if none)
        run: |
          set -euo pipefail
          export CODEGEN_OUTPUT_DIR="${CODEGEN_OUTPUT_DIR:-$(pwd)/ios/build/generated}"
          export TEMPLATE_SRC_DIR="${TEMPLATE_SRC_DIR:-$(pwd)/src/specs}"
          npm run codegen || true

      # ---- Ensure project exists for pods ----
      - name: Install XcodeGen
        run: brew install xcodegen || true

      - name: Generate Xcode project (if project.yml exists)
        run: |
          set -euo pipefail
          if [ -f ios/project.yml ]; then
            (cd ios && xcodegen generate)
          fi

      # ---- Pods (no bundler) ----
      - name: CocoaPods repo update (best-effort)
        run: pod repo update || true

      - name: Pod install
        run: |
          set -euo pipefail
          cd ios
          pod install --repo-update

      # ---- Archive unsigned (Release / iphoneos) ----
      - name: Build unsigned archive (Release, iphoneos)
        run: |
          set -euo pipefail
          mkdir -p build
          cd ios

          xcodebuild clean \
            -workspace MyOfflineLLMApp.xcworkspace \
            -scheme MyOfflineLLMApp \
            -configuration Release

          ARCHIVE_PATH="../build/MyOfflineLLMApp.xcarchive"
          xcodebuild archive \
            -workspace MyOfflineLLMApp.xcworkspace \
            -scheme MyOfflineLLMApp \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$ARCHIVE_PATH" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            DEVELOPMENT_TEAM="" \
            SKIP_INSTALL=NO \
            BUILD_LIBRARY_FOR_DISTRIBUTION=NO \
            -resultBundlePath ../build/MyOfflineLLMApp_ipa.xcresult \
            | tee ../build/xcodebuild_ipa.log

      - name: Package unsigned IPA
        run: |
          set -euo pipefail
          cd build
          APP_PATH="MyOfflineLLMApp.xcarchive/Products/Applications/MyOfflineLLMApp.app"
          if [ ! -d "$APP_PATH" ]; then
            echo "::error::App not found at $APP_PATH"
            exit 1
          fi
          rm -rf Payload
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          /usr/bin/zip -qry offLLM-unsigned.ipa Payload
          /usr/bin/zip -qry MyOfflineLLMApp.app.zip "$APP_PATH"

      - name: Upload unsigned IPA & logs
        uses: actions/upload-artifact@v4
        with:
          name: ios-unsigned-ipa
          path: |
            build/offLLM-unsigned.ipa
            build/MyOfflineLLMApp.app.zip
            build/xcodebuild_ipa.log
            build/MyOfflineLLMApp.xcarchive
            build/MyOfflineLLMApp_ipa.xcresult
          if-no-files-found: error
          compression-level: 6
