name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  js-ci:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max_old_space_size=4096
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.4
          cache: npm

      - name: Install deps from lockfile
        run: npm ci

      - name: Generate Turbo headers (no-op if none)
        run: |
          set -euo pipefail
          export CODEGEN_OUTPUT_DIR="${CODEGEN_OUTPUT_DIR:-$(pwd)/ios/build/generated}"
          export TEMPLATE_SRC_DIR="${TEMPLATE_SRC_DIR:-$(pwd)/src/specs}"
          npm run codegen || true

      - name: Format check
        run: npm run format:check

      - name: Unit tests
        run: npm run test:ci

      - name: Run ESLint (no warnings allowed)
        run: npm run lint:ci

  ios-ci:
    runs-on: macos-14
    env:
      NODE_OPTIONS: --max_old_space_size=4096
    steps:
      - uses: actions/checkout@v4

      # --- Xcode selection & guard (RN 0.81 needs >=16.1) ---
      - name: Select Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Verify Xcode is >= 16.1
        run: |
          set -euo pipefail
          VER=$(xcodebuild -version | awk '/Xcode/ {print $2}')
          echo "Selected Xcode: $VER"
          [[ "$VER" =~ ^16\. ]] || { echo "❌ Requires Xcode 16.x"; exit 1; }

      # --- Node & JS deps BEFORE pods (codegen may create headers) ---
      - name: Setup Node (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.4
          cache: npm

      - name: Install JS deps from lockfile
        run: npm ci

      - name: Generate Turbo headers (no-op if none)
        run: |
          set -euo pipefail
          export CODEGEN_OUTPUT_DIR="${CODEGEN_OUTPUT_DIR:-$(pwd)/ios/build/generated}"
          export TEMPLATE_SRC_DIR="${TEMPLATE_SRC_DIR:-$(pwd)/src/specs}"
          npm run codegen || true

      # --- Ensure an .xcodeproj exists (harmless if not using XcodeGen) ---
      - name: Install XcodeGen
        run: brew install xcodegen || true

      - name: Generate Xcode project (if project.yml exists)
        run: |
          set -euo pipefail
          if [ -f ios/project.yml ]; then
            (cd ios && xcodegen generate)
          fi

      # --- CocoaPods (no Bundler to avoid 3.3 gemset mismatch) ---
      - name: CocoaPods repo update (best-effort)
        run: pod repo update || true

      - name: Pod install
        run: |
          set -euo pipefail
          cd ios
          pod install --repo-update

      # --- Patch script phases to add output paths & remove Hermes "Replace Hermes" ---
      - name: Harden script phases & scrub Hermes
        run: |
          set -euo pipefail
          cd ios
          # ensure xcodeproj gem is present
          ruby -e "begin; require 'xcodeproj'; rescue LoadError; system('gem install xcodeproj -v \"~>1.27\" --no-document'); require 'xcodeproj'; end"

          ruby - <<'RUBY'
            require 'xcodeproj'

            def harden(project_path)
              return unless File.exist?(project_path)
              proj = Xcodeproj::Project.open(project_path)
              proj.targets.each do |t|
                t.shell_script_build_phases.each do |p|
                  # Add a harmless derived output to silence "will run every build" warnings
                  if (p.output_paths.nil? || p.output_paths.empty?) && (p.files_references.nil? || p.files_references.empty?)
                    safe = (p.name || 'Phase').gsub(/\W/,'_')
                    p.output_paths = ["$(DERIVED_FILE_DIR)/#{safe}.touch"]
                  end
                  # Prefer outputs-driven execution
                  p.always_out_of_date = '0' if p.respond_to?(:always_out_of_date)
                end

                # Remove Hermes "Replace Hermes" phases if any
                t.shell_script_build_phases
                  .select { |p| (p.name || '') =~ /\[Hermes\]\s*Replace Hermes/i }
                  .each { |p| t.build_phases.delete(p) }
              end
              proj.save
            end

            harden('Pods/Pods.xcodeproj')
            harden('MyOfflineLLMApp.xcodeproj')
          RUBY

          # Assert Hermes phase is gone
          if grep -Riq --include=project.pbxproj "Replace Hermes" Pods MyOfflineLLMApp.xcodeproj; then
            echo "::error::Hermes 'Replace Hermes' phase still present after hardening"
            exit 1
          fi

      # --- Debug build on a simulator that exists on the runner ---
      - name: Show available simulator destinations (debug aid)
        run: |
          xcodebuild -workspace ios/MyOfflineLLMApp.xcworkspace \
                     -scheme MyOfflineLLMApp \
                     -configuration Debug \
                     -showdestinations || true

      - name: Clean & Build (Debug, iPhone 16 Pro / iOS 18.2)
        run: |
          set -euo pipefail
          mkdir -p build
          cd ios

          xcodebuild clean \
            -workspace MyOfflineLLMApp.xcworkspace \
            -scheme MyOfflineLLMApp \
            -configuration Debug

          # In case the scheme treats warnings as errors, explicitly turn it off here
          xcodebuild \
            -workspace MyOfflineLLMApp.xcworkspace \
            -scheme MyOfflineLLMApp \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.2' \
            GCC_TREAT_WARNINGS_AS_ERRORS=NO \
            -resultBundlePath ../build/MyOfflineLLMApp.xcresult \
            build \
            | tee ../build/xcodebuild.log

      # --- Upload artifacts for diagnosis ---
      - name: Upload build logs & result bundle
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-outputs
          path: |
            build/xcodebuild.log
            build/MyOfflineLLMApp.xcresult
          if-no-files-found: warn
          compression-level: 6

  ios-ipa:
    runs-on: macos-14
    needs: ios-ci
    env:
      NODE_OPTIONS: --max_old_space_size=4096
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Verify Xcode is >= 16.1
        run: |
          set -euo pipefail
          VER=$(xcodebuild -version | awk '/Xcode/ {print $2}')
          echo "Selected Xcode: $VER"
          [[ "$VER" =~ ^16\. ]] || { echo "❌ Requires Xcode 16.x"; exit 1; }

      - name: Setup Node (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.4
          cache: npm

      - name: Install JS deps from lockfile
        run: npm ci

      - name: Generate Turbo headers (no-op if none)
        run: |
          set -euo pipefail
          export CODEGEN_OUTPUT_DIR="${CODEGEN_OUTPUT_DIR:-$(pwd)/ios/build/generated}"
          export TEMPLATE_SRC_DIR="${TEMPLATE_SRC_DIR:-$(pwd)/src/specs}"
          npm run codegen || true

      - name: Install XcodeGen
        run: brew install xcodegen || true

      - name: Generate Xcode project (if project.yml exists)
        run: |
          set -euo pipefail
          if [ -f ios/project.yml ]; then
            (cd ios && xcodegen generate)
          fi

      - name: CocoaPods repo update (best-effort)
        run: pod repo update || true

      - name: Pod install
        run: |
          set -euo pipefail
          cd ios
          pod install --repo-update

      - name: Build unsigned archive (Release, iphoneos)
        run: |
          set -euo pipefail
          mkdir -p build
          cd ios

          xcodebuild clean \
            -workspace MyOfflineLLMApp.xcworkspace \
            -scheme MyOfflineLLMApp \
            -configuration Release

          ARCHIVE_PATH="../build/MyOfflineLLMApp.xcarchive"
          xcodebuild archive \
            -workspace MyOfflineLLMApp.xcworkspace \
            -scheme MyOfflineLLMApp \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$ARCHIVE_PATH" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            DEVELOPMENT_TEAM="" \
            SKIP_INSTALL=NO \
            BUILD_LIBRARY_FOR_DISTRIBUTION=NO \
            -resultBundlePath ../build/MyOfflineLLMApp_ipa.xcresult \
            | tee ../build/xcodebuild_ipa.log

      - name: Package unsigned IPA
        run: |
          set -euo pipefail
          cd build
          APP_PATH="MyOfflineLLMApp.xcarchive/Products/Applications/MyOfflineLLMApp.app"
          if [ ! -d "$APP_PATH" ]; then
            echo "::error::App not found at $APP_PATH"
            exit 1
          fi
          rm -rf Payload
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          /usr/bin/zip -qry offLLM-unsigned.ipa Payload
          /usr/bin/zip -qry MyOfflineLLMApp.app.zip "$APP_PATH"

      - name: Upload unsigned IPA & logs
        uses: actions/upload-artifact@v4
        with:
          name: ios-unsigned-ipa
          path: |
            build/offLLM-unsigned.ipa
            build/MyOfflineLLMApp.app.zip
            build/xcodebuild_ipa.log
            build/MyOfflineLLMApp.xcarchive
            build/MyOfflineLLMApp_ipa.xcresult
          if-no-files-found: error
          compression-level: 6
