name: CI

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  js-ci:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max_old_space_size=4096

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm  # built-in caching per docs
      # keeps installs fast while using lockfile determinism.

      - name: Install deps from lockfile
        run: npm ci

      - name: Generate Turbo headers (no-op if none)
        run: npm run codegen
        # README: codegen reads src/specs -> headers.

      - name: Lint (if configured)
        run: |
          if [ -f eslint.config.js ] || [ -f .eslintrc ] || [ -f .eslintrc.js ]; then
            npm run lint
          else
            echo "No ESLint config; skipping."
          fi

      - name: Format check
        run: npm run format:check

      - name: Unit tests
        run: npm run test:ci
