name: iOS Simulator

on:
  push:
    branches: [main, master]
  pull_request:

permissions:
  contents: write

jobs:
  build:
    name: Simulator build (iPhone 16 Pro / iOS 18)
    runs-on: macos-15
    env:
      NODE_OPTIONS: --max_old_space_size=4096
      RCT_NEW_ARCH_ENABLED: 1
      USE_HERMES: true
      SCHEME: MyOfflineLLMApp
      CONFIGURATION: Debug
      SIM_DEVICE: iPhone 16 Pro
      BUILD_DIR: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Node deps
        run: npm ci

      - name: Cache Bundler
        uses: actions/cache@v4
        with:
          path: ios/vendor/bundle
          key: ${{ runner.os }}-bundler-${{ hashFiles('ios/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-bundler-

      - name: Bundle config path
        working-directory: ios
        run: bundle config set path vendor/bundle

      - name: Bundle install
        working-directory: ios
        run: bundle install

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Clean DerivedData
        run: rm -rf ~/Library/Developer/Xcode/DerivedData/*

      - name: Generate Xcode project
        run: xcodegen generate --spec ios/project.yml

      - name: Clean CocoaPods sandbox if stale
        working-directory: ios
        run: |
          set -euo pipefail
          rm -f Pods/Manifest.lock
          rm -rf Pods/Headers || true

      - name: Set NODE_BINARY for Xcode scripts
        run: |
          rm -f ios/.xcode.env.local
          printf 'export NODE_BINARY="%s"\n' "$(command -v node)" > ios/.xcode.env

      - name: Install Pods (bundler)
        working-directory: ios
        run: bundle exec pod install --repo-update

      - name: Scrub Hermes script phases
        working-directory: ios
        run: |
          bundle exec ruby ../scripts/strip_hermes_phase.rb Pods/Pods.xcodeproj MyOfflineLLMApp.xcodeproj

      - name: Assert Hermes phase is gone
        run: |
          set -euo pipefail
          if /usr/bin/grep -R --include=project.pbxproj --line-number -i "Replace Hermes|\[Hermes\]" \
               ios/Pods ios/MyOfflineLLMApp.xcodeproj 2>/dev/null; then
            echo "::error::Forbidden Hermes 'Replace Hermes' script phase still present after scrubbing."
            exit 1
          fi
          echo "✅ Hermes phase not found."

      - name: Snapshot Pods shell script phases (forensics)
        if: always()
        run: |
          mkdir -p build
          ruby - <<'RUBY' > build/pods_shell_scripts.txt
            require 'xcodeproj'
            p = Xcodeproj::Project.open('ios/Pods/Pods.xcodeproj')
            p.targets.each do |t|
              t.build_phases
               .select { |bp| bp.isa == 'PBXShellScriptBuildPhase' }
               .each { |bp| puts "#{t.name} :: #{bp.name}" }
            end
          RUBY

      - name: Upload Pods/Xcode projects on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ios-forensics-${{ github.job }}
          path: |
            ios/Podfile.lock
            ios/Pods/Pods.xcodeproj/project.pbxproj
            ios/MyOfflineLLMApp.xcodeproj/project.pbxproj
            build/pods_shell_scripts.txt

      - name: Resolve Swift package dependencies
        run: xcodebuild -resolvePackageDependencies -workspace ios/MyOfflineLLMApp.xcworkspace -scheme MyOfflineLLMApp -UseModernBuildSystem=YES

      - name: Build (Simulator)
        run: |
          set -euo pipefail
          mkdir -p "${BUILD_DIR}"
          xcodebuild \
            -workspace ios/MyOfflineLLMApp.xcworkspace \
            -scheme "${SCHEME}" \
            -configuration "${CONFIGURATION}" \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=${SIM_DEVICE}" \
            -UseModernBuildSystem=YES \
            -parallelizeTargets 'NO' \
            -jobs 1 \
            -resultBundlePath "${BUILD_DIR}/MyOfflineLLMApp.xcresult" \
            CODE_SIGNING_ALLOWED=NO \
            clean build | tee "${BUILD_DIR}/xcodebuild.log" | xcpretty

      # --- Generate CI reports (human + agent) ---
      - name: Generate CI reports
        if: always()
        run: |
          set -euo pipefail
          LOG_PATH="${BUILD_DIR}/xcodebuild.log"
          XCRESULT_PATH="${BUILD_DIR}/MyOfflineLLMApp.xcresult"
          if [ -f "scripts/ci/build_report.py" ]; then
            python3 scripts/ci/build_report.py \
              --log "${LOG_PATH}" \
              --xcresult "${XCRESULT_PATH}" \
              --out REPORT.md \
              --agent report_agent.md \
            || { echo "⚠️ build_report.py failed; falling back to minimal reports."; false; }
          fi
          if [ ! -f REPORT.md ] || [ ! -f report_agent.md ]; then
            {
              echo "# iOS CI Report"
              echo
              echo "- Workflow: ios-simulator"
              echo "- Log: ${LOG_PATH}"
              echo "- XCResult: ${XCRESULT_PATH}"
              echo
              echo "## Notes"
              echo "This is a minimal fallback report generated by CI."
              echo
              echo "## Quick scan"
              if [ -f "${LOG_PATH}" ]; then
                grep -iE "error|failed" "${LOG_PATH}" | tail -n 200 || true
              else
                echo "(no log found)"
              fi
            } > REPORT.md
            {
              echo "# agent_report"
              echo "workflow=ios-simulator"
              echo "log=${LOG_PATH}"
              echo "xcresult=${XCRESULT_PATH}"
              echo "summary_tail_200_errors=$( [ -f "${LOG_PATH}" ] && grep -iE "error|failed" "${LOG_PATH}" | tail -n 200 | sed 's/|/\\|/g' | tr '\n' ' ' || echo 'none' )"
            } > report_agent.md
          fi

      - name: Upload CI reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-ci-reports
          path: |
            REPORT.md
            report_agent.md

      # Commit/push reports only on main branch and non-PR events
      - name: Commit CI reports to repo
        if: always() && github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        run: |
          set -euo pipefail
          git config user.email "ci-bot@users.noreply.github.com"
          git config user.name "ci-bot"
          git add REPORT.md report_agent.md || true
          git diff --cached --quiet && { echo "No report changes to commit."; exit 0; }
          git commit -m "ci: update REPORT.md & report_agent.md [skip ci]" || true
          git push || echo "⚠️ Push failed (likely due to permissions or protected branch)."
