name: iOS Signed – monGARS

on:
  workflow_dispatch:
    inputs:
      export_method:
        description: "Export method: ad-hoc | development | app-store"
        required: false
        default: "ad-hoc"
  push:
    branches: [main, master]

env:
  SCHEME: monGARS
  WORKING_DIR: ios
  DERIVED_DATA: build/DerivedData
  ARCHIVE_PATH: build/monGARS.xcarchive
  EXPORT_DIR: build/export
  RESULT_BUNDLE: build/DerivedData/ResultBundle_build.xcresult
  XCODE_PROJECT_NAME: monGARS.xcodeproj

jobs:
  signing-guard:
    runs-on: ubuntu-latest
    environment: offLLM
    outputs:
      should-run: ${{ steps.check.outputs.should-run }}
    steps:
      - name: Check signing secrets
        id: check
        env:
          P12_BASE64: ${{ secrets.P12_BASE64 }}
          MOBILEPROVISION_BASE64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
        run: |
          set -euo pipefail
          missing=()
          for name in P12_BASE64 MOBILEPROVISION_BASE64 TEAM_ID; do
            if [ -z "${!name:-}" ]; then
              missing+=("$name")
            fi
          done

          if [ "${#missing[@]}" -eq 0 ]; then
            echo "should-run=true" >> "$GITHUB_OUTPUT"
            echo "All signing secrets are configured."
          else
            printf '::warning ::Skipping signed iOS build because the following secrets are not configured: %s\n' "$(IFS=,; echo "${missing[*]}")"
            echo "should-run=false" >> "$GITHUB_OUTPUT"
          fi

  build-signed-ipa:
    needs: signing-guard
    if: ${{ needs.signing-guard.outputs.should-run == 'true' }}
    runs-on: macos-15
    environment: offLLM
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select latest Xcode 16 on macOS 15
        run: bash scripts/ci/select_xcode.sh 16

      - name: Verify required secrets
        run: |
          set -euo pipefail
          for name in P12_BASE64 MOBILEPROVISION_BASE64 TEAM_ID; do
            if [ -z "${!name:-}" ]; then echo "::error ::Missing secret: $name"; exit 1; fi
          done
        env:
          P12_BASE64: ${{ secrets.P12_BASE64 }}
          MOBILEPROVISION_BASE64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          TEAM_ID: ${{ secrets.TEAM_ID }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Bun
        if: hashFiles('bun.lockb') != ''
        uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7

      - name: Install JS deps
        run: |
          if [ -f yarn.lock ]; then yarn install --frozen-lockfile; fi
          if [ -f pnpm-lock.yaml ]; then corepack enable && pnpm i --frozen-lockfile; fi
          if [ -f bun.lockb ]; then bun install --no-save; fi

      - name: Install Ruby & CocoaPods
        run: |
          ruby -v
          gem install bundler -N || true
          sudo gem install cocoapods -N
          pod --version

      - name: Generate Xcode project (XcodeGen)
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          if ! command -v xcodegen >/dev/null 2>&1; then brew install xcodegen; fi
          xcodegen generate
          test -d "${{ env.XCODE_PROJECT_NAME }}" || { echo "::error ::XcodeGen failed"; exit 1; }

      - name: Pod install
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          pod repo update
          pod install --verbose

      - name: (Optional) Pre-archive prep
        run: |
          bash scripts/ci/prep-ios-unsigned-archive.sh || true

      - name: Write signing files
        id: files
        working-directory: ${{ env.WORKING_DIR }}
        env:
          P12_BASE64: ${{ secrets.P12_BASE64 }}
          MOBILEPROVISION_BASE64: ${{ secrets.MOBILEPROVISION_BASE64 }}
        run: |
          set -euo pipefail
          mkdir -p signing
          echo "$P12_BASE64" | base64 -d > signing/cert.p12
          echo "$MOBILEPROVISION_BASE64" | base64 -d > signing/profile.mobileprovision
          ls -la signing

      - name: Import signing into temp keychain
        id: signing
        working-directory: ${{ env.WORKING_DIR }}
        env:
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        run: |
          set -euo pipefail
          KEYCHAIN_NAME="build-signing.keychain-db"
          KEYCHAIN_PWD="$(uuidgen)"
          bash ../scripts/ci/import_signing.sh \
            signing/cert.p12 "${P12_PASSWORD:-}" signing/profile.mobileprovision \
            "$KEYCHAIN_NAME" "$KEYCHAIN_PWD"

      - name: Determine bundle id & export method
        id: meta
        env:
          BUNDLE_ID: ${{ secrets.BUNDLE_ID }}
          INPUT_METHOD: ${{ github.event.inputs.export_method }}
          SECRET_METHOD: ${{ secrets.EXPORT_METHOD }}
        run: |
          set -euo pipefail
          BUNDLE_ID="${BUNDLE_ID:-com.offllm.monGARS}"
          METHOD="${INPUT_METHOD:-${SECRET_METHOD:-development}}"
          echo "bundle_id=$BUNDLE_ID" >> "$GITHUB_OUTPUT"
          echo "method=$METHOD" >> "$GITHUB_OUTPUT"
          echo "Using bundle id: $BUNDLE_ID, method: $METHOD"

      - name: Generate ExportOptions.plist (robust; no /dev/stdin)
        working-directory: ${{ env.WORKING_DIR }}
        env:
          TEAM_ID: ${{ secrets.TEAM_ID }}
          BUNDLE_ID: ${{ steps.meta.outputs.bundle_id }}
          EXPORT_METHOD_IN: ${{ steps.meta.outputs.method }}
        run: |
          set -euo pipefail

          # Derive PROFILE_NAME from the actual provisioning profile if not exported
          if [[ -z "${PROFILE_NAME:-}" ]]; then
            TMP_PLIST=$(mktemp)
            security cms -D -i signing/profile.mobileprovision > "$TMP_PLIST"
            PROFILE_NAME=$(/usr/libexec/PlistBuddy -c 'Print :Name' "$TMP_PLIST")
            rm -f "$TMP_PLIST"
          fi

          # Determine available codesigning identities
          IDS=""
          if [[ -n "${KEYCHAIN_PATH:-}" && -e "${KEYCHAIN_PATH}" ]]; then
            IDS=$(security find-identity -p codesigning -v "${KEYCHAIN_PATH}" 2>/dev/null | sed -n 's/.*"\(.*\)".*/\1/p' || true)
          else
            IDS=$(security find-identity -p codesigning -v 2>/dev/null | sed -n 's/.*"\(.*\)".*/\1/p' || true)
          fi

          if [[ -n "$IDS" ]]; then
            IDS_NOTICE="${IDS//$'\n'/%0A}"
            echo "::notice ::Detected signing identities:%0A${IDS_NOTICE}"
          else
            echo "::warning ::No codesigning identities detected"
          fi

          HAVE_DISTRIBUTION=0
          if grep -qE 'Apple Distribution|iOS Distribution' <<<"$IDS"; then HAVE_DISTRIBUTION=1; fi
          HAVE_DEVELOPMENT=0
          if grep -q 'Apple Development' <<<"$IDS"; then HAVE_DEVELOPMENT=1; fi

          METHOD="${EXPORT_METHOD_IN:-development}"
          # Xcode 16: "ad-hoc" is deprecated -> "release-testing"
          if [[ "$METHOD" == "ad-hoc" ]]; then METHOD="release-testing"; fi

          # Guard rails: fall back if required identity is missing
          if [[ "$METHOD" == "release-testing" || "$METHOD" == "app-store" ]]; then
            if [[ $HAVE_DISTRIBUTION -eq 0 ]]; then
              echo "::warning ::No Apple Distribution identity; falling back to development export"
              METHOD="development"
            fi
          fi
          if [[ "$METHOD" == "development" && $HAVE_DEVELOPMENT -eq 0 && $HAVE_DISTRIBUTION -eq 1 ]]; then
            echo "::warning ::No Apple Development identity; falling back to release-testing export"
            METHOD="release-testing"
          fi
          if [[ "$METHOD" == "development" && $HAVE_DEVELOPMENT -eq 0 ]]; then
            IDS_ERROR="${IDS:-<none>}"
            IDS_ERROR="${IDS_ERROR//$'\n'/%0A}"
            echo "::error ::No Apple Development identity found. Detected identities:%0A${IDS_ERROR}"
            exit 1
          fi

          : > ExportOptions.plist
          /usr/libexec/PlistBuddy -c "Add :method string $METHOD" ExportOptions.plist
          /usr/libexec/PlistBuddy -c "Add :signingStyle string manual" ExportOptions.plist
          if [[ -n "${TEAM_ID:-}" ]]; then
            /usr/libexec/PlistBuddy -c "Add :teamID string $TEAM_ID" ExportOptions.plist
          fi
          /usr/libexec/PlistBuddy -c "Add :provisioningProfiles dict" ExportOptions.plist
          /usr/libexec/PlistBuddy -c "Add :provisioningProfiles:${BUNDLE_ID} string ${PROFILE_NAME}" ExportOptions.plist
          if [[ "$METHOD" == "development" ]]; then
            /usr/libexec/PlistBuddy -c "Add :signingCertificate string Apple Development" ExportOptions.plist
          else
            /usr/libexec/PlistBuddy -c "Add :signingCertificate string Apple Distribution" ExportOptions.plist
          fi
          /usr/libexec/PlistBuddy -c "Add :stripSwiftSymbols bool true" ExportOptions.plist
          /usr/libexec/PlistBuddy -c "Add :compileBitcode bool false" ExportOptions.plist

          /usr/libexec/PlistBuddy -c "Print" ExportOptions.plist

      - name: Build & Archive (signed)
        working-directory: ${{ env.WORKING_DIR }}
        env:
          TEAM_ID: ${{ secrets.TEAM_ID }}
          KEYCHAIN_PATH: ${{ env.KEYCHAIN_PATH }}
          BUNDLE_ID: ${{ steps.meta.outputs.bundle_id }}
        run: |
          set -euo pipefail
          test -n "$TEAM_ID"
          # Prefer the workspace made by CocoaPods
          PROJECT_FLAG="-workspace monGARS.xcworkspace"
          mkdir -p "${DERIVED_DATA}"
          xcodebuild \
            $PROJECT_FLAG \
            -scheme "${SCHEME}" \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath "${ARCHIVE_PATH}" \
            -derivedDataPath "${DERIVED_DATA}" \
            -resultBundlePath "${RESULT_BUNDLE}" \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="${TEAM_ID}" \
            PRODUCT_BUNDLE_IDENTIFIER="${BUNDLE_ID}" \
            OTHER_CODE_SIGN_FLAGS="--keychain ${KEYCHAIN_PATH}" \
            clean archive | xcpretty && exit ${PIPESTATUS[0]}

      - name: Export signed IPA
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          set -euo pipefail
          rm -rf "${EXPORT_DIR}"
          bash ../scripts/ci/export_ipa.sh "${ARCHIVE_PATH}" "ExportOptions.plist" "${EXPORT_DIR}"

      - name: Upload IPA & logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: monGARS-signed-ipa
          path: |
            ios/build/export/*.ipa
            ios/ExportOptions.plist
            ios/build/DerivedData/ResultBundle_build.xcresult
          if-no-files-found: warn

      - name: Cleanup keychain
        if: always()
        run: |
          set -euo pipefail
          # variables exported by import_signing.sh in GITHUB_ENV
          if [[ -n "${ORIGINAL_DEFAULT_KEYCHAIN:-}" ]]; then
            security default-keychain -s "${ORIGINAL_DEFAULT_KEYCHAIN}" || true
          fi
          if [[ -n "${ORIGINAL_KEYCHAIN_LIST:-}" ]]; then
            RESTORE_KEYCHAINS=()
            while IFS= read -r kc; do [[ -z "$kc" ]] || RESTORE_KEYCHAINS+=("$kc"); done <<<"${ORIGINAL_KEYCHAIN_LIST}"
            [[ ${#RESTORE_KEYCHAINS[@]} -gt 0 ]] && security list-keychains -d user -s "${RESTORE_KEYCHAINS[@]}" || true
          fi
          [[ -n "${KEYCHAIN_PATH:-}" && -e "${KEYCHAIN_PATH}" ]] && security delete-keychain "${KEYCHAIN_PATH}" || true
