name: iOS Dev-Signed IPA (Free Account)

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 1" # Mondays 13:00 UTC → preempt the 7-day expiry

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-15
    env:
      XCODE_VERSION: "16.4"
      BUNDLE_ID: ${{ secrets.BUNDLE_ID }}
      TEAM_ID: ${{ secrets.TEAM_ID }}
      APP_NAME: ${{ secrets.APP_NAME }}
      P12_BASE64: ${{ secrets.P12_BASE64 }}
      P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
      MOBILEPROVISION_BASE64: ${{ secrets.MOBILEPROVISION_BASE64 }}
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode_${XCODE_VERSION}.app"

      - name: Set up Node
        uses: actions/setup-node@cd2651c46231bc0d6f48d6b34433b845331235fe
        with:
          node-version: "20"
          cache: "npm"

      - name: Set up Ruby
        uses: ruby/setup-ruby@5bd297a9a5eaf3266385dc3b2d4b3f2a8036f2ce
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Install CocoaPods
        run: |
          gem install cocoapods -v 1.15.2 --no-document
          pod repo update

      - name: NPM install
        run: npm ci

      - name: Pods install
        working-directory: ios
        run: pod install --verbose

      - name: Pre-build sanity checks
        run: |
          test -f ios/monGARS.xcworkspace/contents.xcworkspacedata || echo "::warning::Xcode workspace missing; ensure Pods created it"
          test -f index.js || (echo "::error::index.js missing"; exit 1)

      - name: Build dev-signed IPA (fastlane)
        run: bundle exec fastlane ios build_dev_ipa

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@6b55eaf8f0e9c8d178f7c926b2110bcd9f589c67
        with:
          name: ios-dev-ipa
          path: |
            build/output/*.ipa
            build/DerivedData/Archive.xcarchive
            build/DerivedData/ResultBundle_archive.xcresult
