name: Release (iOS+Android)

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write # to create a Release

jobs:
  build-ios:
    uses: ./.github/workflows/ios-unsigned.yml
    secrets: inherit

  build-android:
    uses: ./.github/workflows/android.yml
    secrets: inherit

  publish:
    runs-on: ubuntu-latest
    needs: [build-ios, build-android]
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create GitHub Release and attach artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
